define("money/nls/list", {
	root: {
		title: "Transactions",
		add : 'add',
		about: 'About',
		backup: 'Backup & Restore',
		backupCreate: 'Sync now',
		transition: 'Transition',
		
		currencySelectNote: "Please select your <b>home currency</b>. It will be used for all statistics and reports.<br/>Your choice can not be changed later without application reset.",
	    currencySelectTitle: "Home currency",
	    currencySelectButton: "CONTINUE",
		
		restoreUpload: 'Restore from saved file',
		cancel: 'cancel',
		back : 'back',
		edit: 'edit',
		login: 'login',
		remove: 'remove',
		daily: 'day sum',
		menu: 'menu',
		reports: 'reports',
		settings: 'settings',
		syncNow: 'sync now',
		restore: 'Restore from Dropbox',
		clearRemote: 'Clear Dropbox data',
		clear: 'Delete all data & settings',
		clearTrans: 'Delete all transactions',
		timespan: 'Timespan',
		
		last31: 'Last month',
		lastMonth: 'Select month...',
		customTimespan: 'Current month',
		allTimespan: 'All the time',
		
		charts: 'summary',
		menuTitle: 'R5M Finance',
		expence: 'expence',
		expences: 'expences',
		income:'income',
		incomes:'incomes',
		transfer: 'transfer',
		transfers: 'transfers',
		settings:'Settings',
		stats:'Summary',
		about:'About R5M',
		transactions:'Transactions',
		type:'Type',
		
		amount: 'Amount',
		account: 'Account',
		accounts: 'Accounts',
		accountTo: 'To account',
		
		tags: 'Tags',
		categories: 'Categories',
		date: 'Date',
		description:'Description',
		amountHolder: '0.00',
		accountHolder : 'default',
		ok: 'ok',
		details: "details",
		summary: "summary",
		
		noTransactionsTitle: "Welcome to the R5M finance",
		noTransactions: 'Tap <b>"Add"</b> button to add your first transaction',
		noExpencesTitle: 'No expencies this day',
		noIncomesTitle: 'No incomes this day',
		noTransfersTitle: 'No transfers this day',
		noTransactionsSimple: 'Tap <b>"Add"</b> button to add on'
		
	},
	'ru-ru': true
});
