define({
  root: {
	//for v0.3.x
	about		: 'about',
	accounts 	: 'accounts',
	amountTitle	: 'amount',
	//settings page
	backup		: 'backup',
	backupCreate	: 'create backup',
	backupRestore	: 'backup & restore',
	backupUpload: 'choose file...',
	categoriesTitle 	: 'categories',
	closeMenu	: 'main menu',
	create		: 'create',
	dateTitle	: 'date',
	descriptionTitle	: 'description',
	expences	: 'expences',
	incomes		: 'incomes',
	transfers	: 'transfers',
	locale		: 'locale & language',
	myData		: 'my data',
	options		: 'options',
	personal	: 'personalization',
	preferences	: 'preferences',
	reports		: 'reports',
	restore		: 'restore',
	selectLanguage: 'select locale & language',
	selectTheme : 'select theme',
	statistics		: 'statistics',
	systemLang	: 'system locale',
	total		: 'total',
	theme		: 'theme',
	themeLight 	: 'light (default)',
	themeDark 	: 'dark',
	themeTango 	: 'tango dark',
	transition 	: 'Transition',
	

	
	//for v0.2.x
	type		: 'Type',
	account		: '(to)   Account',
	accountTo	: '(from) Account',
	add			: 'Add',
	cats		: 'Categories',
	date		: 'Date',
	done		: 'Done',
	expence		: 'Expence',
	income		: 'Income',
	transfer	: 'Transfer',
	remove		: 'Remove',
	back		: 'Back',
	choose		: 'Choose',
	chooseCats	: 'Categories',
	cancel		: 'Cancel',
	edit		: 'Edit',
	ok			: 'Ok',
	yes			: 'Yes',
	no			: 'No',
	monthly		: 'Transactions (monthly)',
	daily		: 'Transactions (daily)',
	details		: 'Transaction details',
	welcome			: "Welcome to Money <sup style=\'font-weight:bold;font-size:75%;color:#0099CC\'>R5M</sup>",
	welcomeLoading	: "Please, wait a second, while application is loading...",
	noTransactions	: "Welcome to Money by R5M!<br/>This is the main screen<br/>Tap <b>"+'"+"'+"</b> button to add transaction at any time",
	tapToSettings	: "Tap <b>Settings</b> button to set up <b>accounts</b> and <b>budgets</b>",
	settings	: "Settings",
	summary		: "Reports",
	transactions: "Transactions",
	
	onComplete: "Operation complete",
	onDeleting: "Deleting record...",
	onDelete: "Transaction deleted",	
	errorOccured: "Error occured during performing operation",
	pleaseWait :"Please, wait a second...",
	
	onRestartNeeded : "Please, restart application",
	personalData : "My data",
	personalAccounts: "My accounts",
	personalCategories: "My categories",
	
	backupRestore: "Backup & Restore",
	preferences: "Preferences",
	lang: "Locale",
	
  },
  "en-us" : true,
  "ru-ru" : true
});
