define("money/nls/ru-ru/app.nls", {
	//for v0.3.x
	about		: 'о приложении',
	accounts 	: 'счета',
	amountTitle		: 'сумма',
	//settings page
	backup		: 'создать',
	backupCreate	: 'сохранить',
	backupRestore	: 'резервное копирование',
	backupUpload: 'выбрать файл...',
	categoriesTitle 	: 'категории',
	descriptionTitle	: 'описание',
	create		: 'сохранить',
	locale		: 'язык',
	myData		: 'мои данные',
	closeMenu	: 'главное меню',
	personal	: 'персонализация',
	preferences	: 'настройки',
	restore		: 'восстановить',
	selectLanguage: 'выберите язык',
	selectTheme : 'выберите тему оформления',
	statistics		: 'статистика',
	systemLang	: 'настройки системы',
	theme		: 'тема оформления',
	themeLight 	: 'light (по умолчанию)',
	themeDark 	: 'dark',
	themeTango 	: 'tango dark',
	
	//v0.2.x
  	type		:'Тип',
	account		:'Счет',
	accountTo	:'Счет (куда)',
	add			:'Добавить',
	amount		:'Сумма',
	cats		:'Категории',
	date		:'Дата',
	done		:'Готово',
	description	:'Описание',
	expence		:'Расход',
	income		:'Доход',
	transfer	:'Перевод',
	remove		:'Удалить',
	back		:'Назад',
	cancel		:'Отмена',
	choose		:'Выберите',
	chooseCats	:'Категории',
	
	details		:'Детали',
	edit		:'Редактировать',
	ok			:'Ok',
	yes			:'Да',
	no			:'Нет',
	monthly		:'Транзакции',
	daily		:'Один день',
	details		:'детали транзакции',
	welcome			: "Добро пожаловать в Money <sup style='font-weight:bold;font-size:75%;color:#0099CC'>R5M</sup>",
	welcomeLoading	: "Загрузка приложения...",
	noTransactions	: "Добро пожаловать в MoneyR5M!<br/>Нажмите <b>"+'"+"'+"</b>, чтобы добавить транзакцию в любой момент времени",
	tapToSettings	: "Вы находитесь на главной странице приложения<br/>Нажмите кнопку <b>Настроки</b>, чтобы задать <b>счета</b> и <b>бюджет</b>",
	settings	: "Настройки",
	summary		: "Отчеты",
	transactions: "Транзакции",
	
	onComplete: "Операция выполнена",
	onDeleting: "Удаление...",
	onDelete: "Транзакция удалена",
	errorOccured: "Во время выполнения операции произошла ошибка",
	pleaseWait :"Пожалуйста, подождите...",
	
	onRestartNeeded : "Пожалуйста, перезапустите приложение",
	
	personalData : "Персональные данные",
	personalAccounts: "Мои счета",
	personalCategories: "Категории транзакций",
	
	
});
